### ISSUE TITLE
Reference to the Publication of "FastCovarianceMatrixAdaptation"

### ISSUE THREAD

**Issue by kayuksel** [DuaneNielsen/cma-es#1]
Hello @DuaneNielsen , can you please point me to the reference of "FastCovarianceMatrixAdaptation" so that I can know what algorithm is exactly used here and give reference to it if necessary. I am not sure if this is an established one from literature or something for example that includes modifications from yourself. I was also only able to run it without errors on constant mode). Thank you very much! Have a great weekend.

**Comment by DuaneNielsen** [comment]
Hey.  Sorry, been reading up on stereo vision and not doing much code recently.

This is what I followed.  In the appendix matlab code is provided, which is mostly what I used to figure out the algorithm.

[The CMA Evolution Strategy: A Tutorial](https://arxiv.org/abs/1604.00772)

**Comment by kayuksel** [comment]
Thank you so much!
